### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by burakkgunduzz** [aralroca/next-translate-plugin#13]
**What version of this package are you using?**
"next-translate-plugin": "^2.0.2"

**What operating system, Node.js, and npm version?**
v18.15.0

**What happened?**
after I upgraded next-translate and added next-translate-plugin my builds started to fail. Everything works correctly in development server but I am not able to build my app. I am using nx monorepo and all the stack trace and errors points to my lib folders interestingly. Everything was working before with next v12.1.5 and  next-translate v1.4.0

**What did you expect to happen?**
It should of work.

**Are you willing to submit a pull request to fix this bug?**
No

---
**Stack Trace
```Module parse failed: Unexpected token (39:4)
File was processed with these loaders:
 * ../../node_modules/next-translate-plugin/lib/cjs/loader.js
You may need an additional loader to handle the result of these loaders.
| 
|   return (
>     <div className={cx([styles.embla, options.wrapperClass])}>
|       <div className={styles.embla__viewport} ref={viewportRef}>
|         <div className={styles.embla__container}>

Import trace for requested module:
../../libs/core/components/web/ImageSlider/index.js
../../libs/core/components/web/index.js
```

---

if I downgrade next version to 13.1.1 (from v13.2.4)then I get the below error
```
info  - Collecting page data .Error: You can not use getInitialProps with getStaticProps. To use SSG, please remove your getInitialProps
    at /Users/burakgunduz/Documents/development/work/fg-client/node_modules/next/dist/build/utils.js:913:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/burakgunduz/Documents/development/work/fg-client/node_modules/next/dist/trace/trace.js:79:20)
info  - Collecting page data .
 >  NX   Failed to collect page data for /_error```

**Comment by aralroca** [comment]
Thanks to report it @burakkgunduzz, would you create a reproducible repo about this issue to take a look what is happening? Thanks a lot!

**Comment by burakkgunduzz** [comment]
Hey @aralroca thanks for your attention! I will try to create in a day or two hopefully.

**Comment by burakkgunduzz** [comment]
PS: when I remove imports from lib in my example repo, everything works correctly again. Wondering, if it is related with rollup or monorepo structure? Further investigating.

**Comment by burakkgunduzz** [comment]
Seems like a breaking change in next.js and it affected nx. I am giving some links for further info. Please take a look and close this issue if you are sure that this bug is not related with next-translate-plugin. @aralroca 
 => https://github.com/vercel/next.js/issues/46374#issuecomment-1476717052
=> https://github.com/nrwl/nx/issues/15214

**Comment by burakkgunduzz** [comment]
I was able to successfully build my apps after upgrading to latest nx version and exporting my next.config as 
```
module.exports = async (phase) => {
  let updatedConfig = plugins.reduce((acc, fn) => fn(acc), nextConfig);
  updatedConfig = await withNx(updatedConfig)(phase);
  updatedConfig = withSentryConfig(updatedConfig, sentryWebpackPluginOptions);
  return updatedConfig;
}
``` 
for further info https://github.com/nrwl/nx/issues/15794 
Also, I am closing this issue since this is not a problem related to next-translate-plugin
