### ISSUE TITLE
Unexpected injection of __Next_Translate__Page

### ISSUE THREAD

**Issue by rusted-love** [aralroca/next-translate-plugin#23]
next-translate-plugin 2.0.5

yarn v1.22.19

NextJs version 13.4.3

When I put "use client" directive into some "utility" (not component), for example:
path: `src/utils/hooks/useRouterObject`
```
"use client"
import {useCallback, useMemo} from 'react'

import useRouterString from './useRouterString'

const useRouterObject = <T extends Record<string, unknown>>(
	param: string,
	defaultValue: T
): [T, (object: T) => void] => {
    //Code does not matter here
}
export default useRouterObject

```
I get a weird runtime error caused by injecting `return <__Next_Translate__Page__188429434c9__ {...props} />`  into my function.
Is this behaviour expected?

**Comment by aralroca** [comment]
No, is not expected. Thanks to report this error @rusted-love
