### ISSUE TITLE
Improve detection of getInitialProps

### ISSUE THREAD

**Issue by sunwrobert** [aralroca/next-translate-plugin#24]
**What version of this package are you using?**
2.0.5
**What operating system, Node.js, and npm version?**

**What happened?**
If I have a page like this
```
// src/pages/verify-email.ts
import { AccountVerifyEmailPage } from "features/account/components/AccountVerifyEmailPage"

export default AccountVerifyEmailPage

// src/features/account/components/AccountVerifyEmailPage
export const AccountVerifyEmailPage: NextPage = () => {
  ...
}

AccountVerifyEmailPage.getInitialProps = ctx => {
  ...
}

```

next-translate-plugin doesn't properly detect that this `verify-email` page is using `getInitialProps` and instead tries to load `getServerSideProps`, which then causes a conflict/error on the page. I currently have to do a workaround where I wrap it with a no-op HoC in order to force getInitialProps. Is there a way we can improve this detection?

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by amosbastian** [comment]
I have the same problem 😞 Can you show the workaround you have?

**Comment by sunwrobert** [comment]
@amosbastian 

Something like this:

```

/**
 * This is a no-op HOC that forces next-translate to properly load translations on getInitialProps.
 */
export const forceNextTranslateGetInitialProps = (page: NextPage) => {
  if (!page.getInitialProps) {
    throw new Error(
      "This HOC should only be used on pages with getInitialProps",
    )
  }

  return page
}

export default forceNextTranslateGetInitialProps(HomePage)

```

**Comment by aralroca** [comment]
`getInitialProps` is a legacy Next.js API. So the priority of this issue is very low. I recommend you to use the new loaders or the new folder system (app dir). That said, feel free to open a PR fixing it and you are welcome to do so. Thanks!

**Comment by aralroca** [comment]
Duplicated of https://github.com/aralroca/next-translate-plugin/issues/8
