### ISSUE TITLE
Client component: Error: Cannot read properties of undefined (reading '_context')

### ISSUE THREAD

**Issue by amosbastian** [aralroca/next-translate-plugin#28]
**What version of this package are you using?**

2.3.0-canary.3

**What operating system, Node.js, and npm version?**

* MacOS
* Node.js: v18.14.0
* npm: 9.3.1

**What happened?**

I was checking https://github.com/aralroca/next-translate-plugin/pull/22 because I was getting hydration errors when using translations in client components. By coincidence @aralroca had just commented that it should be fixed in 2.3.0-canary.3, so I decided to try it out. Then I got this error:

```
Error: Cannot read properties of undefined (reading '_context')
```

I created a repository:

https://github.com/amosbastian/nx-next-translate

```
npm i
npx nx serve web
```

**What did you expect to happen?**

I expected it to run

**Are you willing to submit a pull request to fix this bug?**

I could if necessary

**Comment by aralroca** [comment]
Thanks to share, probably is about appDir detection in monorepo, that we changed to support to work with pages folder and app folder together to facilitate migration. I'm going to take a look!

**Comment by amosbastian** [comment]
I'm also having some trouble with redirecting from `/` to `/en` (default locale), (`request.nextUrl.pathname` in `middleware.ts` is equal to `/sign-in` when it should be `/en/sign-in`). I think this is caused by the `nextTranslate` plugin in `next.config.js` removing the locale. If so, then how do you recommend always redirecting to the default locale if no locale is included (something like shown [here])?

**Comment by aralroca** [comment]
@amosbastian try this prerelease:

- `next-translate` version [**`2.3.0-canary.3`**](https://github.com/aralroca/next-translate/releases/tag/2.3.0-canary.3)
- `next-translate-plugin` version [**`2.3.0-canary.7`**](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.7)

After [`2.3.0-canary.6`](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.6) of the plugin we have given direct support to `/[lang]` dynamic route to solve the rewrite and [redirect issues](https://github.com/vercel/next.js/issues/49883) that middleware has in Next.js >= 13.3.

To work your example after updating the dependencies:

- Change `[locale]` to `[lang]`
- Remove the middleware
- Change navigation to `/${params.lang}/sign-in` (?lang= is not necessary)
- If you need to do redirects, you can do it inside `[lang]/layout.ts`

example redirects in `[lang]/layout.ts`, also `Link` navigations fixed:

```js
import i18n from '../../i18n';
import Link from 'next/link';
import { redirect } from 'next/navigation'

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}) {
  // Redirect pages without lang like /sign-in to /en/sign-in/ (default language)
  if (!i18n.locales.includes(params.lang)) redirect(`/${i18n.defaultLocale}/${params.lang}`)

  return (
    <html lang={params.lang}>
      <body>
        <header style={{ display: 'flex', flexDirection: 'row', gap: '1rem' }}>
          <Link href={`/${params.lang}`}>/</Link>
          <Link href={`/${params.lang}/sign-in`}>/sign-in</Link>
        </header>
        {children}
        {params.lang}
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: '1rem',
            marginTop: '1rem',
          }}
        >
          {params.lang === 'nl' ? (
            <Link href="/en">EN</Link>
          ) : (
            <Link href="/nl">NL</Link>
          )}
        </div>
      </body>
    </html>
  );
}
```

**Comment by aralroca** [comment]
@amosbastian I updated the with-app-directory example:

https://github.com/aralroca/next-translate/tree/master/examples/with-app-directory
