### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by alirezas** [aralroca/next-translate-plugin#30]
**What version of this package are you using?**
^2.0.5

**What operating system, Node.js, and npm version?**
v18.16.0

**What happened?**
I reproduced the whole error here https://codesandbox.io/p/sandbox/trusting-babycat-pfn545

I'm using nextjs 13 with app directory when i trying to add ReactQueryDevtools i get this error:

```
./node_modules/.pnpm/@tanstack+react-query-devtools@4.29.12_@tanstack+react-query@4.29.12_react-dom@18.2.0_react@18.2.0/node_modules/@tanstack/react-query-devtools/build/lib/Explorer.mjs
Module parse failed: Unexpected token (263:13)
File was processed with these loaders:
 * ./node_modules/.pnpm/next-translate-plugin@2.0.5_next-translate@2.0.6/node_modules/next-translate-plugin/lib/cjs/loader.js
You may need an additional loader to handle the result of these loaders.
|       }
| 
>       return <Explorer {...props} />
|     }
|
```

its working without ReactQueryDevtools

```
"@tanstack/react-query": "^4.29.12",
"@tanstack/react-query-devtools": "^4.29.12",
```

ReactQueryProvider.tsx
```
"use client"

import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import { useState } from "react"

type Props = {
  children: React.ReactNode
}

export default function ReactQueryProvider({ children }: Props) {
  const [queryClient] = useState(() => new QueryClient())

  return (
    <QueryClientProvider client={queryClient}>
      {children}
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  )
}
```

**Comment by ajames14-chwy** [comment]
➕ 1, I am in the exact same situation and this only happens when ReactQueryDevtools are enabled.

**Comment by aralroca** [comment]
Can you try if this solves the problem? https://github.com/aralroca/next-translate/blob/master/docs/hoist-non-react-statics.md

**Comment by aralroca** [comment]
I found the error https://github.com/aralroca/next-translate-plugin/pull/34

**Comment by aralroca** [comment]
@ajames14-chwy Should be fixed in `next-translate-plugin` version [`2.3.0-canary.5`](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.5). Would be great if you give here some feedback if is already solved. Thanks! 😊

**Comment by ajames14-chwy** [comment]
No luck on my end, still hit the same error.

```sh

Module parse failed: Unexpected token (263:13)
File was processed with these loaders:
 * ./node_modules/next-translate-plugin/lib/cjs/loader.js
You may need an additional loader to handle the result of these loaders.
|       }
|
>       return <Explorer {...props} />
|     }
|

Import trace for requested module:
./node_modules/@tanstack/react-query-devtools/build/lib/Explorer.mjs
./node_modules/@tanstack/react-query-devtools/build/lib/devtools.mjs
./node_modules/@tanstack/react-query-devtools/build/lib/index.mjs
./src/providers/index.tsx

```

**Comment by aralroca** [comment]
It should not transform it🤔. Are you sure you have updated the package-lock.json or yarn.lock with the next-translate-plugin version 2.3.0-canary.5? Thanks

**Comment by alirezas** [comment]
I Updated to `next-translate": "2.3.0-canary.3` and `next-translate-plugin": "2.3.0-canary.5` and problem solved.

**Comment by ajames14-chwy** [comment]
I only updated the plugin, when updating both packages everything resolved. Thanks
