### ISSUE TITLE
Label are not rendered after page reload

### ISSUE THREAD

**Issue by brunoscopelliti** [aralroca/next-translate-plugin#57]
```
"next": "^13.4.8"
"next-translate": "^2.4.4"
"next-translate-plugin": "^2.4.4"
```

```
node v18.15.0
macOS Ventura
```

It seems `useTranslations` after page reload does't work for server components.

I've created this [repro.zip](https://github.com/aralroca/next-translate-plugin/files/11940770/repro.zip) where you can reproduce the issue.

- Navigate to page-1, and refresh the page. You should be able to see the label correctly.

- Navigate to page-2, and refresh the page. At this point the label is not rendered anymore.

**Comment by brunoscopelliti** [comment]
Can't replicate with version [2.5.0-canary.1](https://github.com/aralroca/next-translate-plugin/releases/tag/2.5.0-canary.1).

**Comment by aralroca** [comment]
@brunoscopelliti thanks to report it and share the repro example. I close it since we fixed this problem with conflicts with layout namespaces or loading pages and with 2.5.0-canary.3 I see that it is working fine again.
