### ISSUE TITLE
Translations inside pages/.../app/... folders stopped working

### ISSUE THREAD

**Issue by nickredmark** [aralroca/next-translate-plugin#60]
1.4.4, linux, node 20.0.0, npm 9.6.4

In our project we happen to have an `pages/app` folder, which has nothing to do with next.js's new `app` folder (which, if I understand correctly, should be outside `pages`).
Upgrading from 2.0.5 to 2.4.4 caused all translations inside the `pages/app` folder to stop working.
It happens for any page with the following path structure: `pages/**/app/**`

**Comment by aralroca** [comment]
Thanks to report it @nickredmark

**Comment by aralroca** [comment]
@nickredmark it should work in next-translate-plugin [2.5.0-canary.3](https://github.com/aralroca/next-translate-plugin/releases/tag/2.5.0-canary.3) prerelease. Would be great if you can confirm that everything is working fine in your project now. Thanks 😊🙏
