### ISSUE TITLE
getInitialProps inside _app.js not being called

### ISSUE THREAD

**Issue by aureliopita-au** [aralroca/next-translate-plugin#8]
**What version of this package are you using?**
    "next": "^13.2.3",
    "next-translate": "^2.0.2",
    "next-translate-plugin": "^2.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"

**What operating system, Node.js, and npm version?**
MacOS, Node v16.18.0, npm 8.19.2.

**What happened?**
When using `nextTranslate()` inside `next.config.js`, `getInitialProps` from `_app` stops working.

**What did you expect to happen?**
`getInitialProps` from `_app` keeps working.

**Are you willing to submit a pull request to fix this bug?**
Not at the moment.

**Reproducible repo**
Based on the `basic` example from your repo. Just added a `getInitialProps` to `_app`. 
https://github.com/aureliopita-au/next-translate-getInitialProps-bug

**Comment by mrtnzlml** [comment]
👍 I just encountered the same issue. I originally thought I implemented `getInitialProps` incorrectly, but it turns out it was not called at all. After some debugging, I noticed that [`config.skipInitialProps`](https://github.com/aralroca/next-translate/blob/4898199b522077db6661cace7cf7637360e9e93e/src/appWithI18n.tsx#L59) is internally set to "true" (incorrectly, probably because of this plugin). 🤔

**Comment by micahjonas** [comment]
I have encountered the same issue in our nextjs setup.

**Comment by amosbastian** [comment]
Did you guys find a solution to this? @aralroca any ideas?

**Comment by aralroca** [comment]
I think the error is related in this line of code:

https://github.com/aralroca/next-translate-plugin/blob/83c658603af659715bf7479b665e25180fad4f8f/src/index.ts#L75-L79

We replaced all regex by the TypeScript parser, but it probably has using a bad way to detect the `getInitialProps`. Feel free to PR to fix this.

**Comment by danielpid** [comment]
Hi @aralroca, 
I implemented a fix for this, could you add me as a collaborator so I can open a PR and continue the discussion there?
Thanks!

**Comment by aralroca** [comment]
Thanks so much @danielpid !!

**Comment by aralroca** [comment]
@danielpid is already available in 2.5.3-canary.1, please confirm that is working fine in your projects before close this issue! Thanks

**Comment by danielpid** [comment]
@aralroca I confirm it works on my projects. 
Thanks!

**Comment by aralroca** [comment]
Cool!!!
