### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by GenisDiaz** [aralroca/next-translate-plugin#9]
**What version of this package are you using?**
2.0.2
**What operating system, Node.js, and npm version?**
- Node: v18.14.2

**What happened?**

When I use  nextTranslate in the next.config.js then I see the message `Critical dependency: the request of a dependency is an expression` in the console when I try to run the app, then the translations are not working at all.

I'm using the newest nextjs 13.2.4 version with the appDir functionality instead of pages. 

I don't know if I'm doing something wrong or maybe it's something new in the newest version because in other apps with older nextjs version I'm using next-translation instead of next-translation-plugin and the other ones are working good.

**Comment by aralroca** [comment]
I tried to reproduce it in the latest version and I can't reproduce it. Maybe is solved with this related issue: https://github.com/aralroca/next-translate-plugin/pull/32 Can you confirm that now is working for your in the latest version? Thanks!

**Comment by bluelakee02** [comment]
I created a fix https://github.com/aralroca/next-translate-plugin/pull/72
Here is a patch if somebody needs it right away https://github.com/bluelakee02/next-translate-plugin-patch

**Comment by zakidze** [comment]
> I created a fix #72 Here is a patch if somebody needs it right away https://github.com/bluelakee02/next-translate-plugin-patch

HERRROOOOOOO

**Comment by aralroca** [comment]
Already available in 2.6.1 👍  Thanks for the contribution @bluelakee02
